name: Release
on:
  release:
    types: [published]
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v1
      with:
        python-version: '3.8'
        architecture: x64
    - run: sudo apt install python3-venv -y; curl https://install.python-poetry.org | python3 - --version 1.2.0b1
    - run: poetry install
    - run: poetry run flake8
    - run: poetry run black .
    - run: poetry run mypy .
    - run: poetry run python3 -m  xdoctest hmp_aviel
    - run: poetry run pytest --typeguard-packages=hmp_aviel --cov
    - run: poetry build
    - run: poetry publish --username=__token__ --password=${{ secrets.PYPI_TOKEN }}
