name: Tests
on: push
jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.7', '3.8']
    name: Python ${{ matrix.python-version }}
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}
        architecture: x64
    - run: sudo apt install python3-venv -y; curl https://install.python-poetry.org | python3 - --version 1.2.0b1
    - run: poetry install
    - run: poetry run flake8
    - run: poetry run black .
    - run: poetry run mypy .
    - run: poetry run python3 -m  xdoctest hmp_aviel
    - run: poetry run pytest --typeguard-packages=hmp_aviel --cov
    - run: coverage xml --fail-under=0
    - run: poetry run codecov
      env:
        CODECOV_TOKEN: ${{secrets.CODECOV_TOKEN}}
